const SUPABASE_URL="https://tfidkfvuzsfvebstbgcv.supabase.co/rest/v1/";const SUPABASE_ANON_KEY="sb_publishable_KToTfVS_FwufyHAn1QUzwQ_rRdYqyIx";const ready=!SUPABASE_URL.startsWith("YOUR_")&&!SUPABASE_ANON_KEY.startsWith("YOUR_");const sb=ready?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;let user=null,signup=false,mood=null;
const $=id=>document.getElementById(id),show=id=>$(id).classList.remove("hidden"),hide=id=>$(id).classList.add("hidden"),close=()=>document.querySelectorAll(".modal").forEach(x=>x.classList.add("hidden"));function authMode(s){signup=s;$("authEyebrow").textContent=s?"START YOUR PRIVATE SPACE":"WELCOME BACK";$("authTitle").textContent=s?"Create your MindCampus account":"Log in to MindCampus";document.querySelectorAll("#nameWrap,#collegeWrap").forEach(x=>x.classList.toggle("hidden",!s));$("authForm").querySelector("button").textContent=s?"Create account":"Log in";$("switch").textContent=s?"Already have an account? Log in":"New here? Create an account";$("authMsg").textContent="";show("auth")}
$("loginBtn").onclick=()=>authMode(false);$("signupBtn").onclick=()=>authMode(true);$("heroSignup").onclick=()=>authMode(true);$("heroLogin").onclick=()=>authMode(false);$("cta").onclick=()=>authMode(true);$("switch").onclick=()=>authMode(!signup);document.querySelectorAll("[data-close]").forEach(x=>x.onclick=close);document.querySelectorAll(".modal").forEach(x=>x.onclick=e=>{if(e.target===x)close()});
$("authForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("authMsg").textContent="Connect Supabase first — see SETUP.md.";return}$("authMsg").textContent="Please wait…";try{if(signup){const n=$("name").value.trim(),c=$("college").value.trim();const r=await sb.auth.signUp({email:$("email").value.trim(),password:$("password").value,options:{data:{full_name:n,college:c}}});if(r.error)throw r.error;if(!r.data.session){$("authMsg").textContent="Account created. Check your email, then log in.";return}}else{const r=await sb.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(r.error)throw r.error}close();const s=await sb.auth.getSession();user=s.data.session?.user||null;ui();dash()}catch(x){$("authMsg").textContent=x.message||"Something went wrong."}};
async function ui(){if(!user){hide("userMenu");show("loginBtn");show("signupBtn");return}hide("loginBtn");hide("signupBtn");show("userMenu");const n=user.user_metadata?.full_name||user.email.split("@")[0];$("avatar").textContent=n[0].toUpperCase();$("userLabel").textContent=n}
$("avatar").onclick=()=>$("drop").classList.toggle("hidden");$("logoutBtn").onclick=async()=>{await sb.auth.signOut();user=null;ui();close()};$("dashboardBtn").onclick=()=>{hide("drop");dash()};
document.querySelectorAll("[data-mood]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-mood]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");mood=b.dataset.mood;$("checkMsg").textContent="Selected: "+mood});
$("checkin").onclick=async()=>{if(!user)return authMode(true);if(!mood)return $("checkMsg").textContent="Choose a mood first.";const r=await sb.from("mood_checkins").insert({user_id:user.id,mood});$("checkMsg").textContent=r.error?r.error.message:"Saved privately to your account ✓";if(!r.error)loadDash()};
async function dash(){if(!user)return authMode(false);show("dash");await loadDash()}$("refresh").onclick=loadDash;async function loadDash(){if(!sb||!user)return;const n=user.user_metadata?.full_name||user.email.split("@")[0];$("welcome").textContent="Welcome back, "+n.split(" ")[0]+" 👋";const m=await sb.from("mood_checkins").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(8);const a=await sb.from("appointments").select("*").eq("user_id",user.id).order("appointment_date",{ascending:true});const ms=m.data||[],as=a.data||[];$("latest").textContent=ms[0]?.mood||"—";$("latestDate").textContent=ms[0]?new Date(ms[0].created_at).toLocaleString():"No check-ins yet";const nx=as.find(x=>new Date(x.appointment_date+"T"+x.appointment_time)>=new Date());$("next").textContent=nx?.support_type||"—";$("nextDate").textContent=nx?nx.appointment_date+" · "+nx.appointment_time:"No appointment booked";$("history").innerHTML=ms.length?ms.map(x=>`<p>${x.mood} <span style="float:right">${new Date(x.created_at).toLocaleDateString()}</span></p>`).join(""):"<p>No check-ins yet.</p>"}
$("bookBtn").onclick=()=>{close();show("booking")};document.querySelectorAll(".book").forEach(x=>x.onclick=()=>user?show("booking"):authMode(true));$("bookingForm").onsubmit=async e=>{e.preventDefault();const r=await sb.from("appointments").insert({user_id:user.id,support_type:$("type").value,appointment_date:$("date").value,appointment_time:$("time").value,status:"requested"});$("bookMsg").textContent=r.error?r.error.message:"Appointment saved ✓";if(!r.error)setTimeout(()=>{close();dash()},700)};$("demo").onclick=()=>show("demoModal");$("demoForm").onsubmit=e=>{e.preventDefault();$("demoMsg").textContent="Demo request captured ✓";e.target.reset()};
(async()=>{if(sb){const s=await sb.auth.getSession();user=s.data.session?.user||null;sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;ui()})}ui()})();
